import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/styles.module.scss'
import ExpandCircleDownOutlinedIcon from '@mui/icons-material/ExpandCircleDownOutlined';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Karina Macancela | Nice to meet!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.banner}>
          <div className={styles.left}></div>
          <div className={styles.right}>
            <h1>
              Hello, I'm<br/><span className={styles.highlight}>Karina Macancela.</span>
            </h1>
            <div className={styles.center}>
              <ExpandCircleDownOutlinedIcon fontSize="large" />
            </div>
          </div>
        </div>
        <div className={styles.section}>
          <h1 className={styles.title}>Recent Projects</h1>
          <div className={styles.grid}>
            <div className={styles.card}>
              <h2 className={styles.title}>Atrilyx</h2>
            </div>
            <div className={styles.card}>
              <h2 className={styles.title}>Login Portal</h2>
            </div>
            <div className={styles.card}>
              <h2 className={styles.title}>Ecommerce Store</h2>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
